version: '3'

services:
   mysql:
      image: mysql:latest
      environment:
         MYSQL_ROOT_PASSWORD: password
         MYSQL_DATABASE: rschir
      volumes:
         - rschir-data:/var/lib/mysql
      networks:
         - rschir-network

   server:
      build: .
      restart: always
      ports:
         - '8080:8080'
      environment:
         SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/rschir
         SPRING_DATASOURCE_USERNAME: root
         SPRING_DATASOURCE_PASSWORD: password
         SERVER_PORT: 8080
      depends_on:
         - mysql
      networks:
         - rschir-network

networks:
   rschir-network:

volumes:
   rschir-data:
